---
Mode: ModalForm
title: KygekJoinUI
content: Change in config.yml
Buttons:
  SimpleForm:
  - ok
  - Hi:say hi
  ModalForm:
    B1:
      name: world
      command: say hello World!
    B2:
      name: player
      command: say hello {player}
...
